modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="gnomed"
version="${file.jarVersion}"
displayName="Gnomed"
displayURL="https://www.curseforge.com/minecraft/mc-mods/gnomed"
authors="Mrbysco"
description='''
Adds a certain gnome to minecraft
'''
credits='''
Im not a Gnelf, I'm not a Gnoblin. I'm a GNOME AND YOU'VE BEEN GNOMED
'''
[[dependencies.gnomed]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.gnomed]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"