modLoader="javafml"
loaderVersion="[38,)"
license="MIT"

[[mods]]
modId="gnomed"
version="${file.jarVersion}"
displayName="Gnomed"
displayURL="https://www.curseforge.com/minecraft/mc-mods/gnomed"
authors="Mrbysco"
description='''
Adds a certain gnome to minecraft
'''
credits='''
Im not a Gnelf, I'm not a Gnoblin. I'm a GNOME AND YOU'VE BEEN GNOMED
'''
[[dependencies.gnomed]]
modId="minecraft"
mandatory=true
versionRange="[1.18,1.19)"
ordering="NONE"
side="BOTH"